Configuracao.create(cd_empresa: 1, parametro: 'diretorio_listener', valor: '/var/coamo/unifacedes/r96_coamo_des/proclisting')
Configuracao.create(cd_empresa: 1, parametro: 'extensao_leitura', valor: 'all')
Configuracao.create(cd_empresa: 1, parametro: 'ultimo_diretorio', valor: 'proclisting/')
Configuracao.create(cd_empresa: 1, parametro: 'ultima_alteracao', valor: '2021 03 03 12 22 51')
Configuracao.create(cd_empresa: 1, parametro: 'nome_arq_result', valor: 'coamo_desenv')
Configuracao.create(cd_empresa: 1, parametro: 'servidor_http', valor: 'http://localhost:3000/componentes')
Configuracao.create(cd_empresa: 1, parametro: 'servidor_http_funcao', valor: 'http://localhost:3000/funcaos')

Configuracao.create(cd_empresa: 2, parametro: 'diretorio_listener', valor: '/var/coamo/unifacedes/r96_coamo_pro/proclisting')
Configuracao.create(cd_empresa: 2, parametro: 'extensao_leitura', valor: 'all')
Configuracao.create(cd_empresa: 2, parametro: 'ultimo_diretorio', valor: 'proclisting/')
Configuracao.create(cd_empresa: 2, parametro: 'ultima_alteracao', valor: '2021 03 03 12 22 51')
Configuracao.create(cd_empresa: 2, parametro: 'nome_arq_result', valor: 'coamo_producao')
Configuracao.create(cd_empresa: 2, parametro: 'servidor_http', valor: 'http://localhost:3000/componentes')
Configuracao.create(cd_empresa: 2, parametro: 'servidor_http_funcao', valor: 'http://localhost:3000/funcaos')

Configuracao.create(cd_empresa: 3, parametro: 'diretorio_listener', valor: '/var/coamo/unifacedes/r97_credi_dsv/proclisting')
Configuracao.create(cd_empresa: 3, parametro: 'extensao_leitura', valor: 'all')
Configuracao.create(cd_empresa: 3, parametro: 'ultimo_diretorio', valor: 'proclisting/')
Configuracao.create(cd_empresa: 3, parametro: 'ultima_alteracao', valor: '2021 03 03 12 22 51')
Configuracao.create(cd_empresa: 3, parametro: 'nome_arq_result', valor: 'credi_desenv')
Configuracao.create(cd_empresa: 3, parametro: 'servidor_http', valor: 'http://localhost:3000/componentes')
Configuracao.create(cd_empresa: 3, parametro: 'servidor_http_funcao', valor: 'http://localhost:3000/funcaos')

Configuracao.create(cd_empresa: 4, parametro: 'diretorio_listener', valor: '/var/coamo/unifacedes/r97_credi_pro/proclisting')
Configuracao.create(cd_empresa: 4, parametro: 'extensao_leitura', valor: 'all')
Configuracao.create(cd_empresa: 4, parametro: 'ultimo_diretorio', valor: 'proclisting/')
Configuracao.create(cd_empresa: 4, parametro: 'ultima_alteracao', valor: '2021 03 03 12 22 51')
Configuracao.create(cd_empresa: 4, parametro: 'nome_arq_result', valor: 'credi_producao')
Configuracao.create(cd_empresa: 4, parametro: 'servidor_http', valor: 'http://localhost:3000/componentes')
Configuracao.create(cd_empresa: 4, parametro: 'servidor_http_funcao', valor: 'http://localhost:3000/funcaos')


Configuracao.create(cd_empresa: 5, parametro: 'diretorio_listener', valor: '/var/coamo/unifacedes/r97_crctb_pro/proclisting')
Configuracao.create(cd_empresa: 5, parametro: 'extensao_leitura', valor: 'all')
Configuracao.create(cd_empresa: 5, parametro: 'ultimo_diretorio', valor: 'proclisting/')
Configuracao.create(cd_empresa: 5, parametro: 'ultima_alteracao', valor: '2021 03 03 12 22 51')
Configuracao.create(cd_empresa: 5, parametro: 'nome_arq_result', valor: 'credi_crctb_pro')
Configuracao.create(cd_empresa: 5, parametro: 'servidor_http', valor: 'http://localhost:3000/componentes')
Configuracao.create(cd_empresa: 5, parametro: 'servidor_http_funcao', valor: 'http://localhost:3000/funcaos')

Configuracao.create(cd_empresa: 6, parametro: 'diretorio_listener', valor: '/var/coamo/unifacedes/r10_coamo_des/proclisting')
Configuracao.create(cd_empresa: 6, parametro: 'extensao_leitura', valor: 'all')
Configuracao.create(cd_empresa: 6, parametro: 'ultimo_diretorio', valor: 'proclisting/')
Configuracao.create(cd_empresa: 6, parametro: 'ultima_alteracao', valor: '2022 12 27 12 22 51')
Configuracao.create(cd_empresa: 6, parametro: 'nome_arq_result', valor: 'coamo10_desenv')
Configuracao.create(cd_empresa: 6, parametro: 'servidor_http', valor: 'http://localhost:3000/componentes')
Configuracao.create(cd_empresa: 6, parametro: 'servidor_http_funcao', valor: 'http://localhost:3000/funcaos')

Configuracao.create(cd_empresa: 7, parametro: 'diretorio_listener', valor: '/var/coamo/unifacedes/r10_coamo_pro/proclisting')
Configuracao.create(cd_empresa: 7, parametro: 'extensao_leitura', valor: 'all')
Configuracao.create(cd_empresa: 7, parametro: 'ultimo_diretorio', valor: 'proclisting/')
Configuracao.create(cd_empresa: 7, parametro: 'ultima_alteracao', valor: '2022 12 27 12 22 51')
Configuracao.create(cd_empresa: 7, parametro: 'nome_arq_result', valor: 'coamo10_producao')
Configuracao.create(cd_empresa: 7, parametro: 'servidor_http', valor: 'http://localhost:3000/componentes')
Configuracao.create(cd_empresa: 7, parametro: 'servidor_http_funcao', valor: 'http://localhost:3000/funcaos')